#!/usr/bin/env python3
"""
sync_schema.py - DataBridge Schema Sync & Optimization Tool v2.0
================================================================
Parses raw MCP schema text dumps and generates:
  1. databridge_schema_summary.json     (full detailed JSON with physical FKs)
  2. databridge_schema_summary_min.json (token-optimized for LLM injection)
  3. databridge_schema_summary.md       (human-readable Markdown catalog)

Physical FK constraints are loaded from physical_fks.json (generated by
querying sys.foreign_keys / pg_constraint). Cross-database relationships
are ONLY sourced from verified record_discovery gotchas — no heuristics.

Usage:
  python sync_schema.py                    # generate all outputs
  python sync_schema.py --verify           # generate + validate
  python sync_schema.py --input-dir DIR    # use custom raw schema dir
"""

import json
import re
import sys
import os
import io
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timezone

# Fix Windows console encoding for emoji/unicode
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

# ─── Configuration ────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR  # output to workspace root

# Databases and their metadata
DATABASES = {
    "InternalApps_QA_DB": {
        "id": "ee7ea832-2773-4043-8c62-1e6175580959",
        "type": "MSSQL",
        "query_format": "T-SQL",
    },
    "Timesheet": {
        "id": "24bad9b8-75eb-4825-8115-0ebb3f1236e8",
        "type": "POSTGRES",
        "query_format": "PostgreSQL",
    },
    "Appraisal": {
        "id": "ee04575e-09ae-4177-b175-8b66e5df5925",
        "type": "POSTGRES",
        "query_format": "PostgreSQL",
    },
}

# Audit/boilerplate columns to strip from the minified output
AUDIT_COLUMNS = {
    "createdby", "createddate", "modifiedby", "modifieddate",
    "createdate", "updatedate", "createuserid", "updateuserid",
    "created_on", "modified_on", "createdat", "updatedat",
    "cerateddate",  # typo in actual schema
    "concurrencykey", "internalkey",
    "createdatetime", "modifieddatetime",
    "updatedby", "updateddate",
}

# Strict prefix for verified cross-db gotchas written by record_discovery
VERIFIED_XREL_PREFIX = "Verified cross-db relationship:"

# Regex to parse the strict format:
# "Verified cross-db relationship: Joins with <db>.<schema>.<table> on <src_col>=<tgt_col>"
VERIFIED_XREL_PATTERN = re.compile(
    r"^Verified cross-db relationship:\s*Joins with\s+"
    r"(\S+)\.(\S+)\.(\S+)\s+on\s+(\w+)\s*=\s*(\w+)$",
    re.IGNORECASE,
)


# ─── Physical FK Loader ──────────────────────────────────────────────────────

def load_physical_fks(fk_path: Path) -> dict:
    """
    Load physical foreign key constraints from physical_fks.json.
    Fallback: Load from physical_foreign_keys root-level key in databridge_schema_summary.json.
    Returns a nested dict: {db_name: {table_full_name: [fk_entries]}}
    """
    if fk_path.exists():
        with open(fk_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        fk_map = {}
        total = 0
        for db_name, tables in data.get("databases", {}).items():
            fk_map[db_name] = tables
            count = sum(len(fks) for fks in tables.values())
            total += count

        print(f"  ✅ Loaded {total} physical FK constraints from {fk_path.name}")
        return fk_map

    # Fallback to loading from databridge_schema_summary.json
    summary_path = fk_path.parent / "databridge_schema_summary.json"
    if summary_path.exists():
        try:
            with open(summary_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            fk_map = data.get("physical_foreign_keys", {})
            if fk_map:
                total = sum(
                    len(fks)
                    for db_fks in fk_map.values()
                    for fks in db_fks.values()
                )
                print(f"  ✅ Loaded {total} physical FK constraints from existing {summary_path.name}")
                return fk_map
        except Exception as e:
            print(f"  ⚠️  Failed to load fallback FK constraints from {summary_path.name}: {e}")

    print(f"  ⚠️  No physical FK source found (checked {fk_path.name} and {summary_path.name})")
    return {}


# ─── Parser ───────────────────────────────────────────────────────────────────

def parse_schema_text(text: str) -> list[dict]:
    """
    Parse the MCP schema text format into structured table definitions.
    Returns a list of table dicts.
    """
    tables = []
    current_table = None
    in_column_table = False
    header_seen = False

    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]

        # Match table header: **schema.TableName** (~123 rows)
        table_match = re.match(
            r'^\*\*([A-Za-z_][A-Za-z0-9_.]*)\\*\*(?:\s*\(~([\d,]+)\s*rows?\))?',
            line
        )
        if table_match:
            if current_table:
                tables.append(current_table)
            full_name = table_match.group(1)
            row_count = table_match.group(2)
            parts = full_name.split(".", 1)
            schema_name = parts[0] if len(parts) > 1 else ""
            table_name = parts[1] if len(parts) > 1 else parts[0]
            current_table = {
                "schema": schema_name,
                "table": table_name,
                "full_name": full_name,
                "row_count": int(row_count.replace(",", "")) if row_count else None,
                "description": "",
                "gotchas": [],
                "recommended_aggregation": "",
                "common_filter": "",
                "columns": [],
            }
            in_column_table = False
            header_seen = False
            i += 1
            continue

        if current_table:
            # Description line (italic): *description text*
            desc_match = re.match(r'^\*(.+)\*$', line)
            if desc_match and not in_column_table:
                current_table["description"] = desc_match.group(1).strip()
                i += 1
                continue

            # Gotcha/warning line
            if line.strip().startswith("- WARNING:") or line.strip().startswith("- CAUTION:") or line.strip().startswith("- NOTE:"):
                gotcha_text = re.sub(r'^-\s*(WARNING|CAUTION|NOTE):\s*', '', line.strip())
                current_table["gotchas"].append(gotcha_text)
                i += 1
                continue

            # Recommended aggregation
            agg_match = re.match(r'^\*\*Recommended Aggregation:\*\*\s*(.+)', line)
            if agg_match:
                current_table["recommended_aggregation"] = agg_match.group(1).strip()
                i += 1
                continue

            # Common filter
            filter_match = re.match(r'^\*\*Common Filter:\*\*\s*(.+)', line)
            if filter_match:
                current_table["common_filter"] = filter_match.group(1).strip()
                i += 1
                continue

            # Column table header row
            if re.match(r'^\|\s*Column\s*\|', line):
                in_column_table = True
                header_seen = True
                i += 1
                continue

            # Column table separator
            if re.match(r'^\|[-|]+\|', line):
                i += 1
                continue

            # Column data row
            if in_column_table and line.startswith("|"):
                parts = [p.strip() for p in line.split("|")]
                # Remove empty first/last from leading/trailing pipes
                parts = [p for p in parts if p != ""]
                if len(parts) >= 2:
                    col_name_raw = parts[0]
                    col_type = parts[1] if len(parts) > 1 else ""
                    col_semantic = parts[2] if len(parts) > 2 else ""
                    col_security = parts[3] if len(parts) > 3 else ""

                    is_pk = "🔑" in col_name_raw
                    col_name = col_name_raw.replace("🔑", "").strip()
                    is_not_null = "NOT NULL" in col_type

                    current_table["columns"].append({
                        "name": col_name,
                        "type": col_type,
                        "semantic": col_semantic,
                        "is_pk": is_pk,
                        "is_not_null": is_not_null,
                        "security": col_security if col_security else None,
                    })
                i += 1
                continue

            # Non-column, non-metadata line - skip
            if line.strip() == "" or line.startswith("##") or line.startswith("**⚠"):
                i += 1
                continue

        i += 1

    if current_table:
        tables.append(current_table)

    return tables


def parse_file(filepath: str) -> list[dict]:
    """Parse a single raw schema text file."""
    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()
    return parse_schema_text(text)


# ─── Verified Cross-DB Relationship Parser ────────────────────────────────────

def extract_verified_cross_db_relationships(
    all_databases: dict,
) -> list[dict]:
    """
    Extract ONLY verified cross-database relationships from record_discovery
    gotchas. These are gotchas that start with the strict prefix:
      "Verified cross-db relationship: Joins with <db>.<schema>.<table> on <src_col>=<tgt_col>"

    Returns a list of structured relationship dicts.
    No heuristics. Only real, execution-verified joins.
    """
    # Build a set of all known table full names per database for validation
    known_tables = {}
    known_columns = {}
    for db_name, db_data in all_databases.items():
        for table in db_data["tables"]:
            full_key = f"{db_name}.{table['full_name']}"
            known_tables[full_key] = True
            col_names = {c["name"].lower() for c in table["columns"]}
            known_columns[full_key] = col_names

    relationships = []
    seen = set()

    for db_name, db_data in all_databases.items():
        for table in db_data["tables"]:
            for gotcha in table.get("gotchas", []):
                if not gotcha.startswith(VERIFIED_XREL_PREFIX):
                    continue

                match = VERIFIED_XREL_PATTERN.match(gotcha)
                if not match:
                    print(f"  ⚠️  Malformed verified xrel gotcha (skipped): {gotcha}")
                    continue

                tgt_db, tgt_schema, tgt_table, src_col, tgt_col = match.groups()
                tgt_full = f"{tgt_schema}.{tgt_table}"

                # Reference integrity check: validate both sides exist
                src_key = f"{db_name}.{table['full_name']}"
                tgt_key = f"{tgt_db}.{tgt_full}"

                src_valid = src_key in known_tables
                tgt_valid = tgt_key in known_tables

                if not src_valid:
                    print(f"  ⚠️  Source table not found in catalog: {src_key} (skipped)")
                    continue
                if not tgt_valid:
                    print(f"  ⚠️  Target table not found in catalog: {tgt_key} (skipped)")
                    continue

                # Validate columns exist
                src_cols = known_columns.get(src_key, set())
                tgt_cols = known_columns.get(tgt_key, set())

                if src_col.lower() not in src_cols:
                    print(f"  ⚠️  Source column '{src_col}' not found in {src_key} (skipped)")
                    continue
                if tgt_col.lower() not in tgt_cols:
                    print(f"  ⚠️  Target column '{tgt_col}' not found in {tgt_key} (skipped)")
                    continue

                # Deduplicate
                dedup_key = f"{src_key}.{src_col}->{tgt_key}.{tgt_col}"
                if dedup_key in seen:
                    continue
                seen.add(dedup_key)

                relationships.append({
                    "type": "verified_cross_db",
                    "source_db": db_name,
                    "source_table": table["full_name"],
                    "source_column": src_col,
                    "target_db": tgt_db,
                    "target_table": tgt_full,
                    "target_column": tgt_col,
                    "notes": gotcha,
                })

    return relationships


# ─── Output Generators ────────────────────────────────────────────────────────

def build_full_json(
    all_databases: dict,
    relationships: list,
    physical_fks: dict,
) -> dict:
    """Build the full detailed JSON output with physical FK constraints."""
    output = {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generator": "sync_schema.py",
            "version": "2.0.0",
            "description": "Comprehensive DataBridge schema catalog with physical FK constraints and verified cross-DB relationships.",
        },
        "databases": {},
        "physical_foreign_keys": physical_fks,
        "cross_database_relationships": relationships,
    }

    for db_name, db_data in all_databases.items():
        db_info = DATABASES[db_name]
        db_fks = physical_fks.get(db_name, {})
        db_entry = {
            "id": db_info["id"],
            "type": db_info["type"],
            "query_format": db_info["query_format"],
            "schemas": {},
        }
        # Group tables by schema
        schema_groups = defaultdict(list)
        for table in db_data["tables"]:
            schema_groups[table["schema"]].append(table)

        for schema_name, tables in sorted(schema_groups.items()):
            schema_entry = {
                "table_count": len(tables),
                "tables": {},
            }
            for table in tables:
                table_entry = {
                    "row_count": table["row_count"],
                    "description": table["description"],
                    "gotchas": [
                        g for g in table["gotchas"]
                        if not g.startswith(VERIFIED_XREL_PREFIX)
                    ],
                    "recommended_aggregation": table["recommended_aggregation"],
                    "common_filter": table["common_filter"],
                    "columns": [],
                }

                # Attach physical FK constraints for this table
                table_fks = db_fks.get(table["full_name"], [])
                if table_fks:
                    table_entry["foreign_keys"] = table_fks

                for col in table["columns"]:
                    col_entry = {
                        "name": col["name"],
                        "type": col["type"],
                        "semantic": col["semantic"],
                        "is_pk": col["is_pk"],
                    }
                    if col.get("security"):
                        col_entry["security"] = col["security"]
                    table_entry["columns"].append(col_entry)
                schema_entry["tables"][table["table"]] = table_entry
            db_entry["schemas"][schema_name] = schema_entry

        output["databases"][db_name] = db_entry

    return output


def build_minified_json(
    all_databases: dict,
    relationships: list,
    physical_fks: dict,
) -> dict:
    """
    Build the token-optimized minified JSON.
    Strips audit columns, compresses column definitions to 'name:type' strings,
    and embeds physical FK constraints as compact 'fk' maps.
    """
    # Minified root-level physical FKs
    min_fks = {}
    for db_name, db_fks in physical_fks.items():
        db_key = "IA_DB" if db_name == "InternalApps_QA_DB" else db_name
        min_fks[db_key] = {}
        for tbl_name, fks in db_fks.items():
            if fks:
                tbl_fk_map = {}
                for fk in fks:
                    ref = fk["references"]
                    tbl_fk_map[fk["column"]] = f"{ref['table']}.{ref['column']}"
                min_fks[db_key][tbl_name] = tbl_fk_map

    output = {
        "_meta": "DataBridge Schema v2 (Minified). Physical FKs included. Use full JSON for column details.",
        "dbs": {},
        "physical_fks": min_fks,
        "xrels": [],  # verified cross-db relationships only
    }

    for db_name, db_data in all_databases.items():
        db_info = DATABASES[db_name]
        db_fks = physical_fks.get(db_name, {})
        db_key = db_name
        # Shorten key for token savings
        if db_name == "InternalApps_QA_DB":
            db_key = "IA_DB"

        db_entry = {"type": db_info["type"], "tbls": {}}
        for table in db_data["tables"]:
            full_name = table["full_name"]

            # Compress columns, stripping audit fields
            cols = []
            pk_cols = []
            for col in table["columns"]:
                if col["name"].lower() in AUDIT_COLUMNS:
                    continue
                short_type = col["type"].replace("character varying", "varchar") \
                    .replace("timestamp with time zone", "timestamptz") \
                    .replace("timestamp without time zone", "timestamp") \
                    .replace("double precision", "float8") \
                    .replace(" NOT NULL", "!")
                cols.append(f"{col['name']}:{short_type}")
                if col["is_pk"]:
                    pk_cols.append(col["name"])

            tbl_entry = {"cols": cols}
            if pk_cols:
                tbl_entry["pk"] = pk_cols[0] if len(pk_cols) == 1 else pk_cols
            if table["description"]:
                tbl_entry["desc"] = table["description"]

            # Only include non-verified gotchas in warnings
            non_xrel_gotchas = [
                g for g in table["gotchas"]
                if not g.startswith(VERIFIED_XREL_PREFIX)
            ]
            if non_xrel_gotchas:
                tbl_entry["warn"] = non_xrel_gotchas

            if table["common_filter"]:
                tbl_entry["filter"] = table["common_filter"]
            if table["recommended_aggregation"]:
                tbl_entry["agg"] = table["recommended_aggregation"]
            if table["row_count"] is not None:
                tbl_entry["rows"] = table["row_count"]

            # Embed physical FK constraints as compact map:
            #   "fk": {"source_col": "target_schema.target_table.target_col"}
            table_fks = db_fks.get(full_name, [])
            if table_fks:
                fk_map = {}
                for fk in table_fks:
                    ref = fk["references"]
                    fk_map[fk["column"]] = f"{ref['table']}.{ref['column']}"
                tbl_entry["fk"] = fk_map

            db_entry["tbls"][full_name] = tbl_entry

        output["dbs"][db_key] = db_entry

    # Verified cross-db relationships (minified)
    for rel in relationships:
        output["xrels"].append({
            "src": f"{rel['source_db']}.{rel['source_table']}.{rel['source_column']}",
            "tgt": f"{rel['target_db']}.{rel['target_table']}.{rel['target_column']}",
            "note": rel["notes"],
        })

    return output


def build_markdown(
    all_databases: dict,
    relationships: list,
    physical_fks: dict,
) -> str:
    """Build the human-readable Markdown catalog with FK relationships."""
    lines = []
    lines.append("# 📊 DataBridge Schema Catalog v2")
    lines.append("")
    lines.append(f"*Auto-generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} by `sync_schema.py` v2.0*")
    lines.append("")
    lines.append("> [!NOTE]")
    lines.append("> Physical FK constraints are sourced from `sys.foreign_keys` (MSSQL) and `pg_constraint` (PostgreSQL).")
    lines.append("> Cross-database relationships are ONLY from verified `record_discovery` entries — zero heuristics.")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Table of Contents
    lines.append("## Table of Contents")
    lines.append("")
    for db_name in all_databases:
        db_info = DATABASES[db_name]
        table_count = len(all_databases[db_name]["tables"])
        anchor = db_name.lower().replace("_", "-").replace(" ", "-")
        lines.append(f"- [{db_name}](#{anchor}) ({db_info['type']}, {table_count} tables)")
    lines.append("- [Foreign Key Relationships](#foreign-key-relationships)")
    lines.append("- [Verified Cross-Database Relationships](#verified-cross-database-relationships)")
    lines.append("- [Quick SQL Snippets](#quick-sql-snippets)")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Per-database sections
    for db_name, db_data in all_databases.items():
        db_info = DATABASES[db_name]
        db_fks = physical_fks.get(db_name, {})
        lines.append(f"## {db_name}")
        lines.append("")
        lines.append(f"| Property | Value |")
        lines.append(f"|----------|-------|")
        lines.append(f"| **ID** | `{db_info['id']}` |")
        lines.append(f"| **Type** | {db_info['type']} |")
        lines.append(f"| **Query Format** | {db_info['query_format']} |")
        lines.append(f"| **Tables** | {len(db_data['tables'])} |")
        fk_count = sum(len(fks) for fks in db_fks.values())
        lines.append(f"| **Physical FKs** | {fk_count} |")
        lines.append("")

        # Group by schema
        schema_groups = defaultdict(list)
        for table in db_data["tables"]:
            schema_groups[table["schema"]].append(table)

        for schema_name, tables in sorted(schema_groups.items()):
            lines.append(f"### Schema: `{schema_name}` ({len(tables)} tables)")
            lines.append("")

            for table in tables:
                row_info = f" (~{table['row_count']:,} rows)" if table["row_count"] else ""
                lines.append(f"#### `{table['full_name']}`{row_info}")
                lines.append("")

                if table["description"]:
                    lines.append(f"*{table['description']}*")
                    lines.append("")

                # Only show non-verified gotchas inline
                non_xrel_gotchas = [
                    g for g in table["gotchas"]
                    if not g.startswith(VERIFIED_XREL_PREFIX)
                ]
                if non_xrel_gotchas:
                    lines.append("> [!WARNING]")
                    for g in non_xrel_gotchas:
                        lines.append(f"> {g}")
                    lines.append("")

                if table["common_filter"] or table["recommended_aggregation"]:
                    if table["common_filter"]:
                        lines.append(f"**Filter:** `{table['common_filter']}`")
                    if table["recommended_aggregation"]:
                        lines.append(f"**Aggregation:** `{table['recommended_aggregation']}`")
                    lines.append("")

                # Column table
                lines.append("| Column | Type | Semantic | PK |")
                lines.append("|--------|------|----------|----|")
                for col in table["columns"]:
                    pk_marker = "🔑" if col["is_pk"] else ""
                    lines.append(f"| {col['name']} | {col['type']} | {col['semantic']} | {pk_marker} |")
                lines.append("")

                # FK table for this specific table
                table_fks = db_fks.get(table["full_name"], [])
                if table_fks:
                    lines.append(f"**Foreign Keys ({len(table_fks)}):**")
                    lines.append("")
                    lines.append("| Source Column | → Target Table | Target Column |")
                    lines.append("|--------------|----------------|---------------|")
                    for fk in table_fks:
                        ref = fk["references"]
                        lines.append(f"| `{fk['column']}` | `{ref['table']}` | `{ref['column']}` |")
                    lines.append("")

        lines.append("---")
        lines.append("")

    # Consolidated FK relationships section
    lines.append("## Foreign Key Relationships")
    lines.append("")
    total_fks = 0
    for db_name in all_databases:
        db_fks = physical_fks.get(db_name, {})
        fk_count = sum(len(fks) for fks in db_fks.values())
        total_fks += fk_count
        lines.append(f"### {db_name} ({fk_count} FKs)")
        lines.append("")
        if db_fks:
            lines.append("| Source Table | Source Column | → Target Table | Target Column |")
            lines.append("|-------------|--------------|----------------|---------------|")
            for table_name in sorted(db_fks.keys()):
                for fk in db_fks[table_name]:
                    ref = fk["references"]
                    lines.append(f"| `{table_name}` | `{fk['column']}` | `{ref['table']}` | `{ref['column']}` |")
            lines.append("")
        else:
            lines.append("*No physical FK constraints found.*")
            lines.append("")

    lines.append(f"**Total: {total_fks} physical FK constraints across all databases.**")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Verified cross-database relationships section
    lines.append("## Verified Cross-Database Relationships")
    lines.append("")
    lines.append("> [!IMPORTANT]")
    lines.append("> These relationships are ONLY recorded after a successful cross-DB query execution.")
    lines.append("> They are written via `record_discovery` and validated against the schema catalog.")
    lines.append("")
    if relationships:
        lines.append("| Source DB | Source Table | Source Column | → Target DB | Target Table | Target Column |")
        lines.append("|----------|-------------|--------------|-------------|--------------|---------------|")
        for rel in relationships:
            lines.append(
                f"| `{rel['source_db']}` | `{rel['source_table']}` | `{rel['source_column']}` "
                f"| `{rel['target_db']}` | `{rel['target_table']}` | `{rel['target_column']}` |"
            )
        lines.append("")
    else:
        lines.append("*No verified cross-database relationships recorded yet.*")
        lines.append("")
        lines.append("> [!TIP]")
        lines.append("> To add a verified relationship, successfully execute a cross-DB query via")
        lines.append("> `execute_federated_query`, then call `record_discovery` with the strict format:")
        lines.append("> ```")
        lines.append('> "Verified cross-db relationship: Joins with <TargetDB>.<schema>.<table> on <src_col>=<tgt_col>"')
        lines.append("> ```")
        lines.append("")

    # Quick SQL snippets section
    lines.append("---")
    lines.append("")
    lines.append("## Quick SQL Snippets")
    lines.append("")
    lines.append("Common query patterns derived from Atlas-enriched metadata:")
    lines.append("")

    # Generate snippets for tables with common filters
    snippet_count = 0
    for db_name, db_data in all_databases.items():
        db_info = DATABASES[db_name]
        for table in db_data["tables"]:
            if table["common_filter"] or table["gotchas"]:
                snippet_count += 1
                lines.append(f"### {db_name}.{table['full_name']}")
                lines.append("")
                if table["common_filter"]:
                    pk_col = next((c["name"] for c in table["columns"] if c["is_pk"]), "*")
                    if db_info["type"] == "MSSQL":
                        lines.append(f"```sql")
                        lines.append(f"-- Active records query")
                        lines.append(f"SELECT {pk_col}, * FROM [{table['schema']}].[{table['table']}]")
                        lines.append(f"WHERE {table['common_filter']};")
                        lines.append(f"```")
                    else:
                        lines.append(f"```sql")
                        lines.append(f"-- Active records query")
                        lines.append(f'SELECT {pk_col}, * FROM "{table["schema"]}"."{table["table"]}"')
                        lines.append(f"WHERE {table['common_filter']};")
                        lines.append(f"```")
                    lines.append("")
                if table["recommended_aggregation"]:
                    lines.append(f"**Recommended Aggregation:** `{table['recommended_aggregation']}`")
                    lines.append("")
                non_xrel_gotchas = [
                    g for g in table["gotchas"]
                    if not g.startswith(VERIFIED_XREL_PREFIX)
                ]
                if non_xrel_gotchas:
                    lines.append("> [!CAUTION]")
                    for g in non_xrel_gotchas:
                        lines.append(f"> {g}")
                    lines.append("")

    if snippet_count == 0:
        lines.append("*No query snippets available — no tables have Atlas-enriched filters.*")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by `sync_schema.py` v2.0.0*")
    lines.append("")

    return "\n".join(lines)


# ─── Main Orchestrator ────────────────────────────────────────────────────────

def main():
    verify = "--verify" in sys.argv
    input_dir = None
    for i, arg in enumerate(sys.argv):
        if arg == "--input-dir" and i + 1 < len(sys.argv):
            input_dir = sys.argv[i + 1]

    print("=" * 60)
    print("  DataBridge Schema Sync & Optimization Tool v2.0.0")
    print("  Physical FKs + Verified Cross-DB Relationships")
    print("=" * 60)
    print()

    # Step 1: Load physical FK constraints
    print("🔑 Loading physical FK constraints...")
    fk_path = SCRIPT_DIR / "physical_fks.json"
    physical_fks = load_physical_fks(fk_path)
    print()

    # Step 2: Discover and parse raw schema files
    all_databases = {}

    if input_dir:
        # Read from a custom directory of raw schema files
        input_path = Path(input_dir)
        print(f"📂 Reading raw schemas from: {input_path}")
        for db_name in DATABASES:
            db_files = sorted(input_path.glob(f"{db_name}_*.txt"))
            tables = []
            for f in db_files:
                print(f"  📄 Parsing {f.name}...")
                tables.extend(parse_file(str(f)))
            all_databases[db_name] = {"tables": tables}
            print(f"  ✅ {db_name}: {len(tables)} tables parsed")
    else:
        # Read from the schema_sources.json mapping
        sources_path = Path(__file__).resolve().parent
        # Check for schema_sources.json in scratch dir or same dir
        candidates = [
            sources_path / "schema_sources.json",
            sources_path.parent / "scratch" / "schema_sources.json",
            Path(r"C:\Users\acharyve\.gemini\antigravity-ide\brain\a6b97e54-7702-4cf2-9e44-d6f31a2b42eb\scratch\schema_sources.json"),
        ]
        mapping_path = None
        for c in candidates:
            if c.exists():
                mapping_path = c
                break

        if mapping_path:
            print(f"📂 Reading schema source mapping: {mapping_path}")
            with open(mapping_path, "r", encoding="utf-8") as f:
                sources = json.load(f)

            for db_name, db_info in sources.items():
                tables = []
                for schema_key, filepath in db_info.get("schema_files", {}).items():
                    if filepath == "inline":
                        continue  # Skip inline schemas (handled separately)
                    fpath = Path(filepath)
                    if fpath.exists():
                        print(f"  📄 Parsing {db_name}/{schema_key}...")
                        parsed = parse_file(str(fpath))
                        tables.extend(parsed)
                        print(f"     → {len(parsed)} tables")
                    else:
                        print(f"  ⚠️  Missing file: {filepath}")
                all_databases[db_name] = {"tables": tables}
                print(f"  ✅ {db_name}: {len(tables)} total tables")
        else:
            print("❌ No schema_sources.json found. Use --input-dir to specify raw schema directory.")
            sys.exit(1)

    print()

    # Step 3: Extract verified cross-database relationships (no heuristics!)
    print("🔗 Extracting verified cross-database relationships...")
    relationships = extract_verified_cross_db_relationships(all_databases)
    print(f"  ✅ Found {len(relationships)} verified cross-database relationships")
    if len(relationships) == 0:
        print("  ℹ️  No verified xrels yet. Execute cross-DB queries and call record_discovery to add them.")
    print()

    # Step 4: Generate outputs
    print("📝 Generating output files...")

    # Full JSON
    full_json = build_full_json(all_databases, relationships, physical_fks)
    full_json_path = OUTPUT_DIR / "databridge_schema_summary.json"
    with open(full_json_path, "w", encoding="utf-8") as f:
        json.dump(full_json, f, indent=2, ensure_ascii=False)
    full_size = full_json_path.stat().st_size
    print(f"  ✅ {full_json_path.name}: {full_size:,} bytes")

    # Minified JSON
    min_json = build_minified_json(all_databases, relationships, physical_fks)
    min_json_path = OUTPUT_DIR / "databridge_schema_summary_min.json"
    with open(min_json_path, "w", encoding="utf-8") as f:
        json.dump(min_json, f, separators=(",", ":"), ensure_ascii=False)
    min_size = min_json_path.stat().st_size
    print(f"  ✅ {min_json_path.name}: {min_size:,} bytes ({min_size/full_size*100:.0f}% of full)")

    # Markdown
    md_content = build_markdown(all_databases, relationships, physical_fks)
    md_path = OUTPUT_DIR / "databridge_schema_summary.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    md_size = md_path.stat().st_size
    print(f"  ✅ {md_path.name}: {md_size:,} bytes")

    # Copy files to backend/app if it exists
    backend_app_dir = SCRIPT_DIR / "backend" / "app"
    if backend_app_dir.exists():
        import shutil
        print("📂 Copying generated schema files to backend app...")
        for filename in ["databridge_schema_summary.json", "databridge_schema_summary_min.json"]:
            src_file = SCRIPT_DIR / filename
            if src_file.exists():
                dest_file = backend_app_dir / filename
                shutil.copy2(src_file, dest_file)
                print(f"  → Copied {filename} to {dest_file}")

    print()

    # Step 5: Summary
    total_tables = sum(len(db["tables"]) for db in all_databases.values())
    total_columns = sum(
        len(col)
        for db in all_databases.values()
        for table in db["tables"]
        for col in [table["columns"]]
    )
    tables_with_gotchas = sum(
        1 for db in all_databases.values()
        for table in db["tables"]
        if table["gotchas"]
    )
    total_fks = sum(
        len(fks)
        for db_fks in physical_fks.values()
        for fks in db_fks.values()
    )

    print("=" * 60)
    print("  Summary")
    print("=" * 60)
    print(f"  Databases:       {len(all_databases)}")
    print(f"  Total tables:    {total_tables}")
    print(f"  Total columns:   {total_columns}")
    print(f"  With gotchas:    {tables_with_gotchas}")
    print(f"  Physical FKs:    {total_fks}")
    print(f"  Verified xrels:  {len(relationships)}")
    print()
    print(f"  Full JSON:       {full_size:>8,} bytes")
    print(f"  Minified JSON:   {min_size:>8,} bytes  (🔥 {(1 - min_size/full_size)*100:.0f}% smaller)")
    print(f"  Markdown:        {md_size:>8,} bytes")
    print("=" * 60)

    # Step 6: Verification (if --verify)
    if verify:
        print()
        print("🔍 Running verification checks...")
        errors = []

        # Check JSON validity
        try:
            with open(full_json_path, "r", encoding="utf-8") as f:
                full_data = json.load(f)
            print("  ✅ Full JSON is valid")
        except json.JSONDecodeError as e:
            errors.append(f"Full JSON is invalid: {e}")
            print(f"  ❌ Full JSON is invalid: {e}")

        try:
            with open(min_json_path, "r", encoding="utf-8") as f:
                min_data = json.load(f)
            print("  ✅ Minified JSON is valid")
        except json.JSONDecodeError as e:
            errors.append(f"Minified JSON is invalid: {e}")
            print(f"  ❌ Minified JSON is invalid: {e}")

        # Check database count
        if len(min_data.get("dbs", {})) != 3:
            errors.append(f"Expected 3 databases, found {len(min_data.get('dbs', {}))}")
            print(f"  ❌ Expected 3 databases in minified JSON")
        else:
            print("  ✅ All 3 databases present in minified JSON")

        # Check total tables > 0
        if total_tables == 0:
            errors.append("No tables parsed")
            print("  ❌ No tables parsed!")
        else:
            print(f"  ✅ {total_tables} tables parsed")

        # Check physical FKs loaded
        if total_fks > 0:
            print(f"  ✅ {total_fks} physical FK constraints loaded")
        else:
            print("  ⚠️  No physical FK constraints loaded")

        # Spot-check: verify FK data appears in minified JSON
        fk_found_in_min = False
        for db_key, db_data in min_data.get("dbs", {}).items():
            for tbl_name, tbl_data in db_data.get("tbls", {}).items():
                if "fk" in tbl_data:
                    fk_found_in_min = True
                    break
            if fk_found_in_min:
                break
        if fk_found_in_min:
            print("  ✅ FK data present in table-level minified JSON")
        elif total_fks > 0:
            errors.append("FK data missing from table-level minified JSON despite physical_fks.json being loaded")
            print("  ❌ FK data missing from table-level minified JSON")
        else:
            print("  ⚠️  No FK data to verify in minified JSON")

        # Verify root-level physical FKs in minified JSON
        root_fks_min = min_data.get("physical_fks", {})
        if total_fks > 0 and not root_fks_min:
            errors.append("Root-level physical_fks missing from minified JSON")
            print("  ❌ Root-level physical_fks missing from minified JSON")
        elif total_fks > 0:
            has_keys = any(len(tables) > 0 for tables in root_fks_min.values())
            if not has_keys:
                errors.append("Root-level physical_fks is empty in minified JSON")
                print("  ❌ Root-level physical_fks is empty in minified JSON")
            else:
                print("  ✅ Root-level physical_fks present in minified JSON")

        # Spot-check: verify FK data appears in full JSON
        fk_found_in_full = False
        for db_name, db_data in full_data.get("databases", {}).items():
            for schema_name, schema_data in db_data.get("schemas", {}).items():
                for tbl_name, tbl_data in schema_data.get("tables", {}).items():
                    if "foreign_keys" in tbl_data:
                        fk_found_in_full = True
                        break
                if fk_found_in_full:
                    break
            if fk_found_in_full:
                break
        if fk_found_in_full:
            print("  ✅ FK data present in table-level full JSON")
        elif total_fks > 0:
            errors.append("FK data missing from table-level full JSON despite physical_fks.json being loaded")
            print("  ❌ FK data missing from table-level full JSON")

        # Verify root-level physical FKs in full JSON
        root_fks_full = full_data.get("physical_foreign_keys", {})
        if total_fks > 0 and not root_fks_full:
            errors.append("Root-level physical_foreign_keys missing from full JSON")
            print("  ❌ Root-level physical_foreign_keys missing from full JSON")
        elif total_fks > 0:
            has_keys = any(len(tables) > 0 for tables in root_fks_full.values())
            if not has_keys:
                errors.append("Root-level physical_foreign_keys is empty in full JSON")
                print("  ❌ Root-level physical_foreign_keys is empty in full JSON")
            else:
                print("  ✅ Root-level physical_foreign_keys present in full JSON")

        # Check verified relationships
        if len(relationships) > 0:
            print(f"  ✅ {len(relationships)} verified cross-database relationships")
        else:
            print("  ℹ️  No verified cross-database relationships yet (expected until first cross-DB query)")

        # Check Markdown file exists and is non-empty
        if md_path.exists() and md_path.stat().st_size > 0:
            print(f"  ✅ Markdown file generated ({md_size:,} bytes)")
        else:
            errors.append("Markdown file is missing or empty")
            print("  ❌ Markdown file is missing or empty")

        print()
        if errors:
            print(f"❌ Verification FAILED with {len(errors)} error(s):")
            for e in errors:
                print(f"   - {e}")
            sys.exit(1)
        else:
            print("✅ All verification checks passed!")

    print()
    print("Done! 🎉")


if __name__ == "__main__":
    main()
